name: Bike Share Prediction Train Test Build and Push Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  train:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: pip install -r bikeshare_project/requirements/requirements.txt
    - name: Train and save pipeline
      run: python bikeshare_project/bikeshare_model/train_pipeline.py
    - uses: actions/upload-artifact@v3
      with:
        name: my-trained-pipeline
        path: bikeshare_project/bikeshare_model/trained_models

  test:
    needs: train
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - uses: actions/download-artifact@v3
        with:
          name: my-trained-pipeline
          path: bikeshare_project/bikeshare_model/trained_models
      - name: Install dependencies
        run: pip install -r bikeshare_project/requirements/test_requirements.txt
      - name: Test with pytest
        run: pytest


  build:
    needs: [train, test]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - uses: actions/download-artifact@v3
        with:
          name: my-trained-pipeline
          path: bikeshare_project/bikeshare_model/trained_models
      - name: Install dependencies
        run: pip install --upgrade build
      #- name: Build package
      #  run: python -m build
      #- uses: actions/upload-artifact@v3
      #  with:
      #    name: my-build-package
      #    path: dist/*.whl

  push-image:
    needs: [train, test, build]
    runs-on: ubuntu-latest
    steps:
    - name: Repo Checkout
      uses: actions/checkout@v2
      
    #- uses: actions/download-artifact@v3
    #  with:
    #    name: my-build-package
    #    path: bikeshare_project/bikeshare_model_api
        
    - name: Login to Docker hub
      env:
        #DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_USER: sameerd13
        #DOCKER_PASSWORD: ${{ secrets.DOCKER_PASS_TOKEN }}
        DOCKER_PASSWORD: tbd
      run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      
    - name: Build the Docker image for Fastapi app
      env:
        #DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_USER: sameerd13
      run: docker build . -f bikeshare_project/Dockerfile -t $DOCKER_USER/bikeshare-fastapi2:latest
      
    - name: Push the Docker Image
      env:
        #DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        DOCKER_USER: sameerd13
      run: docker push $DOCKER_USER/bikeshare-fastapi2
      
    - name: Logout to Docker hub
      run: docker logout
